config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  devise_for :student_exams, controllers: {
               sessions: 'student_exams/sessions'
             }
  
  
  resources :exams, only: [] do
    resources :register, only: [:new, :create]
  end
  
  resources :question, only: [:show]
  patch 'update_answer/:id', :to => 'question#update_answer', as: 'update_answer'
  get 'finish_exam', :to => 'question#finish_exam', as: 'finish_exam'
  root to: 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/exam.rb
class Exam < ApplicationRecord
  
  has_many :exams_questions
  has_many :student_exams
  has_many :questions, through: :exams_questions

  
  
end

app/models/exams_question.rb
class ExamsQuestion < ApplicationRecord

  belongs_to :exam
  belongs_to :question
end

app/models/question.rb
class Question < ApplicationRecord
end

app/models/student.rb
class Student < ApplicationRecord
  has_many :student_exams

  has_many :exams, through: :student_exams

  validates :mobile,:presence => true,
            :numericality => true,
            :length => { :minimum => 10, :maximum => 15 }
  
  def attend_exam(exam)
    if student_exams.where(exam_id: exam.id).present?
      return false
    else
      ex = student_exams.new(exam_id: exam.id)
      ex.save(validate: false)
      return ex
    end
  end

end

app/models/student_exam.rb
class StudentExam < ApplicationRecord

  devise :database_authenticatable
  
  belongs_to :student
  belongs_to :exam
  has_many :student_exams_questions

  after_create :plot_questions

  def plot_questions
    exam.exams_questions.each do |exam_question|
      self.student_exams_questions.new(student_id: self.student_id, student_exam_id: self.id,
                                            question_id: exam_question.question_id, exams_question_id: exam_question.id).save!
    end
  end

  def email
    
  end

  def password_required?
    return false 
  end

  def encrypted_password
    return ""
  end

  def unsolved_questions
    student_exams_questions.map(&:student_answer).select(&:blank?).count
  end

  def solved_questions
    student_exams_questions.map(&:student_answer).reject(&:blank?).count
  end

  def marks
    student_exams_questions.map(&:is_correct).count(true)
  end

  def student_data
    {name: student.name, mobile: student.mobile, unsolved: unsolved_questions, solved: solved_questions, marks: marks, date: created_at.to_date}
  end
end

app/models/student_exams_question.rb
class StudentExamsQuestion < ApplicationRecord

  belongs_to :student
  belongs_to :student_exam
  belongs_to :exams_question
  belongs_to :question

  scope :remaining, -> { where(student_answer: nil) }

  def check_exam
    unless student_answer.nil?
      self.update(is_correct: self.question.answer == self.student_answer)
    end
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def find_exam
    @exam = Exam.find(params[:exam_id])
  end

  def find_student_exam
    @student_exam = StudentExam.find(params[:student_exam_id])
  end



  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:student_id, :exam_id])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:student_id, :exam_id])
  end

  def after_sign_in_path_for(resource)
    question_path(1)
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    
  end
end

app/controllers/question_controller.rb
class QuestionController < ApplicationController

  before_action :authenticate_student_exam!, except: [:finish_exam]

  
  def show
    p current_student_exam
    #@question = ExamsQuestion.where(exam_id: @exam.id, question_id: params[:question_id]).first
    @questions = current_student_exam.student_exams_questions.remaining
    @question = @questions.first
  end

  def update_answer
    @question = current_student_exam.student_exams_questions.find(params[:id])
    if @question.update(question_params)
      if current_student_exam.student_exams_questions.remaining.count > 0 
        redirect_to question_path(1)
      else
        sign_out(current_student_exam)
        redirect_to finish_exam_path
      end
    else
      @questions = current_student_exam.student_exams_questions.remaining
      render :show
    end
  end

  def finish_exam
  end

  def question_params
    params.require(:student_exams_question).permit(:student_answer)
  end 
end

app/controllers/register_controller.rb
class RegisterController < ApplicationController

  before_action :find_exam
  
  def new
    @student = Student.new
  end
  
  def create
    @student = Student.where(mobile: student_params[:mobile]).first
    if @student.nil?
      @student = Student.new(student_params)
    else
      @student.update(student_params)
    end

    if @student.save
      student_exam = @student.attend_exam(@exam)
      if student_exam.present?
        bypass_sign_in(student_exam)
        redirect_to question_path(1)
      else
        redirect_to new_exam_register_path(@exam), notice: "Exam Already Attempted"
      end
    else
      respond_to do |format|
        format.html {render 'new'}
        format.js
      end
    end
  end

  def student_params
    params.require(:student).permit(:name, :address, :mobile)
  end
end

app/controllers/student_exams/sessions_controller.rb
class StudentExams::SessionsController < ApplicationController

  def new
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def inline_errors(model, model_attribute)
    result = ""
    if model.errors[model_attribute].any?
      model.errors[model_attribute].each do |message|
        result += "<li>#{message}</li>"
      end
    end
    return "<ul>#{result}</ul>".html_safe
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/question_helper.rb
module QuestionHelper
end

app/helpers/register_helper.rb
module RegisterHelper
end

app/helpers/student_exams/sessions_helper.rb
module StudentExams::SessionsHelper
end

app/views/home/index.html.erb
<div id="k-body"><!-- content wrapper -->
  <div class="container"><!-- container -->
    <div class="row no-gutter"><!-- row -->
      <div class="col-lg-8 col-md-8"><!-- doc body wrapper -->
        <div class="col-padded"><!-- inner custom column -->
          <div class="row gutter"><!-- row -->
            <div class="col-lg-12 col-md-12">
              <figure class="news-featured-image">
                <%= image_tag("about_us", {class: "img-responsive"}) %>
              </figure>
              <h1 class="page-title">About J. K. Science Academy Islampur</h1>
              <div class="news-body">
                <p class="call-out">
                  To Prepare students of Rural, Semi Urban, and Urban areas for Career in
                  Medical, Engineering, IIT, and IIM institutions through comprehensive 
                  development of knowledge, attitude, and personality.
                </p>
                <p>
                  J. K. SAI is the only institution in Maharashtra giving best
                  resources through physical and intellectual facilities to students. It is 
                  working in semi urban area like Islampur Tal-Walwa, Dist-Sangli and 
                  giving teaching faculties from Kota, Kanpur, Jabalpur, and Delhi. It is 
                  our honest effort to give best resources to our students to prepare them 
                  for different science exams in state and nation. We have tradition since 
                  35 years of teaching and credit to produce a number of doctors, 
                  engineers. The number of successful students varies from 600 students 
                  as doctors and 800 students contributing in society through education 
                  form government and autonomous colleges.
                </p>
                <p>
                  Since last few years, we have aim to develop the facilities to
                  prepare our students for IIT, IIM institutions through exams like JEE 
                  (main and advance),MH-CET.
                </p>
              </div>
            </div>
          </div><!-- row end -->
          <div class="row gutter k-equal-height"><!-- row -->
            <h1 class="">Our Features</h1>
            <ul>
              <li>
                Successful tradition of 35 years of individual teaching through classrooms and counseling. 
              </li>
              <li>
                Successful students at state and national exams.
              </li>
              <li>
                Complete training and preparation for all India Exams.
              </li>
              <li>
                Experience Teaching staff from Kota, Kanpur, Jabalpur, and Delhi.
              </li>
              <li>
                Scholarship for meritorious students.
              </li>
              <li>
                Academic facility of Laboratory, Library, and Study Room.
              </li>
              <li>
                Separate Residence for girls and boys students.
              </li>
              <li>
                Residence at Campus of Institution.
              </li>
              <li>
                All facilities are available at One Building
              </li>
              <li>
                Parents can see daily progress report of the student on Website and SMS.
              </li>
            </ul>
          </div><!-- row end -->
          <div class="">
            <h1 class="page-title">Address</h1>
            <div class="news-body">
              <p class="call-out">
                JK Science Academy <br/>
                KNP Nagar Road no 2-3 <br/>
                Islampur,<br/>
                Tal walwa Dist Sangli<br/>
                Maharashtra (415409)<br/>
                Mobile: 9420674796
                
              </p>
            </div>
          </div>
        </div><!-- inner custom column end -->
      </div><!-- doc body wrapper end -->
      <%# render partial: 'layouts/side_menu' %>
    </div><!-- row end -->
  </div><!-- container end -->
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JKCITest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#"> <%= image_tag("logo", {:style => "width:80px;"}) %>
        </a>
      </nav>
      <% flash.each do |type, msg| %>
      <div class="alert alert-warning alert-dismissible" role="alert">
        <%= msg %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/question/finish_exam.html.erb
<div id="k-body"><!-- content wrapper -->
  <div class="container"><!-- container -->
    <div class="row no-gutter"><!-- row -->
      <div class="col-lg-8 col-md-8"><!-- doc body wrapper -->
        <div class="col-padded"><!-- inner custom column -->
          <div class="row gutter"><!-- row -->
            <div class="col-lg-12 col-md-12">
              <h1 class="page-title">JK Science Academy will get back to you.</h1>
              <figure class="news-featured-image">
                <%= image_tag("about_us", {class: "img-responsive"}) %>
              </figure>
              <h1 class="page-title">About J. K. Science Academy Islampur</h1>
              <div class="news-body">
                <p class="call-out">
                  To Prepare students of Rural, Semi Urban, and Urban areas for Career in
                  Medical, Engineering, IIT, and IIM institutions through comprehensive 
                  development of knowledge, attitude, and personality.
                </p>
                <p>
                  J. K. SAI is the only institution in Maharashtra giving best
                  resources through physical and intellectual facilities to students. It is 
                  working in semi urban area like Islampur Tal-Walwa, Dist-Sangli and 
                  giving teaching faculties from Kota, Kanpur, Jabalpur, and Delhi. It is 
                  our honest effort to give best resources to our students to prepare them 
                  for different science exams in state and nation. We have tradition since 
                  35 years of teaching and credit to produce a number of doctors, 
                  engineers. The number of successful students varies from 600 students 
                  as doctors and 800 students contributing in society through education 
                  form government and autonomous colleges.
                </p>
                <p>
                  Since last few years, we have aim to develop the facilities to
                  prepare our students for IIT, IIM institutions through exams like JEE 
                  (main and advance),MH-CET.
                </p>
              </div>
            </div>
          </div><!-- row end -->
          <div class="row gutter k-equal-height"><!-- row -->
            <h1 class="">Our Features</h1>
            <ul>
              <li>
                Successful tradition of 35 years of individual teaching through classrooms and counseling. 
              </li>
              <li>
                Successful students at state and national exams.
              </li>
              <li>
                Complete training and preparation for all India Exams.
              </li>
              <li>
                Experience Teaching staff from Kota, Kanpur, Jabalpur, and Delhi.
              </li>
              <li>
                Scholarship for meritorious students.
              </li>
              <li>
                Academic facility of Laboratory, Library, and Study Room.
              </li>
              <li>
                Separate Residence for girls and boys students.
              </li>
              <li>
                Residence at Campus of Institution.
              </li>
              <li>
                All facilities are available at One Building
              </li>
              <li>
                Parents can see daily progress report of the student on Website and SMS.
              </li>
            </ul>
          </div><!-- row end -->
          <div class="">
            <h1 class="page-title">Address</h1>
            <div class="news-body">
              <p class="call-out">
                JK Science Academy <br/>
                KNP Nagar Road no 2-3 <br/>
                Islampur,<br/>
                Tal walwa Dist Sangli<br/>
                Maharashtra (415409)<br/>
                Mobile: 9420674796
                
              </p>
            </div>
          </div>
        </div><!-- inner custom column end -->
      </div><!-- doc body wrapper end -->
      <%# render partial: 'layouts/side_menu' %>
    </div><!-- row end -->
  </div><!-- container end -->
</div>

app/views/question/show.html.erb
<figure class="highlight">
  <h3> <%= @question.question.question %></h3>
</figure>
<%= form_with(model: @question, url: update_answer_path(@question)) do |f| %>
<figure class="highlight">
  <h5><%= f.radio_button :student_answer, "opt1" %>
    <label class="form-check-label" for="student_exams_question_student_answer_opt1">
      <%= @question.question.opt1 %>
    </label>
  </h5>
</figure>

<figure class="highlight">
  <h5><%= f.radio_button :student_answer, "opt2" %>
    <label class="form-check-label" for="student_exams_question_student_answer_opt2">
      <%= @question.question.opt2 %>
    </label>
  </h5>
  
</figure>

<figure class="highlight">
  <h5><%= f.radio_button :student_answer, "opt3" %>
    <label class="form-check-label" for="student_exams_question_student_answer_opt3">
      <%= @question.question.opt3 %>
    </label>
  </h5>
</figure>

<figure class="highlight">
  <h5><%= f.radio_button :student_answer, "opt4" %>
    <label class="form-check-label" for="student_exams_question_student_answer_opt4">
      <%= @question.question.opt4 %>
    </label>
  </h5>
</figure>

<%= f.submit "#{@questions.count > 1 ? 'Next' : 'Finish'}", class: "btn btn-primary" %>
<% end %>

app/views/register/create.js.erb
document.getElementById("mobile_errors").innerHTML = "<%= inline_errors(@student, :mobile) %>";

app/views/register/new.html.erb
<%= form_with(model: @student, url: exam_register_index_path(@exam)) do |form| %>
<div class="form-group">
  <label for="student_name">Full Name</label>
  <%= form.text_field :name, class: "form-control" %>
  <div>
    <%= inline_errors(@student, :name) %>
  </div>
</div>
<div class="form-group">
  <label for="student_mobile">Mobile</label>
  <%= form.text_field :mobile, class: "form-control" %>
  <div id="mobile_errors">
    <%= inline_errors(@student, :mobile) %>
  </div>
</div>
<div class="form-group">
  <label for="student_address">Address</label>
  <%= form.text_field :address, class: "form-control" %>
</div>
<%= form.submit  "Start Test", class: "btn btn-primary" %>
<% end %>